"""create notes table

Revision ID: 98320e298e00
Revises: c5eeffc2f968
Create Date: 2026-08-21 20:58:01.194444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98320e298e00'
down_revision: Union[str, Sequence[str], None] = 'c5eeffc2f968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                CASE\n                    WHEN company_id IS NULL THEN 0\n                    ELSE 1\n                END\n                +\n                CASE\n                    WHEN contact_id IS NULL THEN 0\n                    ELSE 1\n                END\n                +\n                CASE\n                    WHEN lead_id IS NULL THEN 0\n                    ELSE 1\n                END\n            ) = 1\n            ', name='ck_notes_exactly_one_related_entity'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_author_id'), 'notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_notes_company_id'), 'notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_notes_contact_id'), 'notes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_notes_lead_id'), 'notes', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_lead_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_contact_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_company_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_author_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
